import type {
    AdminAnnouncement,
    AdminMapHotspot,
    AdminMapPin,
    AdminMission,
    AdminReport,
    AdminResident,
    AdminResidentDetail,
} from '@/Types';
import { severityFromScore } from '@/Lib/mapUtils';

export const demoReports: AdminReport[] = [
    {
        id: '#RP-1042',
        concern_id: 'c1',
        incident_type: 'Clogged drainage',
        type_icon: 'drainage',
        location: 'Mabini St. corner Rizal Ave.',
        ai_severity: 88,
        priority: 'high',
        status: 'ongoing',
        ai_category: 'Infrastructure · Drainage',
        visibility: 'public',
        queue_status: 'under_review',
        submitted_at: 'Jun 17, 9:14 AM',
    },
    {
        id: '#RP-1041',
        concern_id: 'c2',
        incident_type: 'Street flooding',
        type_icon: 'flood',
        location: 'Riverside Ave., Zone 3',
        ai_severity: 76,
        priority: 'high',
        status: 'ongoing',
        ai_category: 'Infrastructure · Flooding',
        visibility: 'public',
        queue_status: 'ai_processed',
        submitted_at: 'Jun 17, 8:42 AM',
    },
    {
        id: '#RP-1038',
        concern_id: 'c3',
        incident_type: 'Noise complaint',
        type_icon: 'noise',
        location: 'Phase 2, Unit 7',
        ai_severity: 42,
        priority: 'med',
        status: 'seen',
        ai_category: 'Sanitation · Noise',
        visibility: 'private',
        queue_status: 'ai_processed',
        submitted_at: 'Jun 16, 11:20 PM',
    },
    {
        id: '#RP-1035',
        concern_id: 'c4',
        incident_type: 'Illegal dumping',
        type_icon: 'waste',
        location: 'Market rear alley',
        ai_severity: 55,
        priority: 'med',
        status: 'seen',
        ai_category: 'Sanitation · Waste',
        visibility: 'public',
        queue_status: 'under_review',
        submitted_at: 'Jun 16, 4:05 PM',
    },
    {
        id: '#RP-1030',
        concern_id: 'c5',
        incident_type: 'Street light out',
        type_icon: 'light',
        location: 'Block 3, Phase 2',
        ai_severity: 35,
        priority: 'low',
        status: 'done',
        ai_category: 'Infrastructure · Street lights',
        visibility: 'public',
        queue_status: 'active',
        submitted_at: 'Jun 15, 6:30 PM',
    },
    {
        id: '#RP-1028',
        concern_id: 'c6',
        incident_type: 'Domestic dispute (VAWC)',
        type_icon: 'noise',
        location: 'Withheld — private case',
        ai_severity: 91,
        priority: 'high',
        status: 'ongoing',
        ai_category: 'Katarungang Pambarangay',
        visibility: 'private',
        queue_status: 'under_review',
        submitted_at: 'Jun 15, 2:10 PM',
    },
    {
        id: '#RP-1022',
        concern_id: 'c7',
        incident_type: 'Spam / duplicate',
        type_icon: 'waste',
        location: 'Duplicate of #RP-1042',
        ai_severity: 12,
        priority: 'low',
        status: 'done',
        ai_category: 'Flagged duplicate',
        visibility: 'public',
        queue_status: 'spam',
        submitted_at: 'Jun 14, 10:00 AM',
    },
    {
        id: '#RP-1019',
        concern_id: 'c8',
        incident_type: 'Fallen electrical line',
        type_icon: 'fire',
        location: 'Zone 4, Block 12',
        ai_severity: 95,
        priority: 'high',
        status: 'ongoing',
        ai_category: 'Infrastructure · Electrical hazard',
        visibility: 'public',
        queue_status: 'active',
        submitted_at: 'Jun 14, 7:45 AM',
    },
];

export function reportCounts(reports: AdminReport[]) {
    return {
        all: reports.length,
        ai_processed: reports.filter((r) => r.queue_status === 'ai_processed').length,
        under_review: reports.filter((r) => r.queue_status === 'under_review').length,
        active: reports.filter((r) => r.queue_status === 'active').length,
        rejected: reports.filter((r) => r.queue_status === 'rejected' || r.queue_status === 'spam').length,
    };
}

export const demoMissions: AdminMission[] = [
    {
        id: '#MS-8902',
        concern_id: 'c1',
        concern_title: 'Clogged drainage on Mabini St.',
        location: 'Mabini St. corner Rizal Ave.',
        assignee: 'Juan Dela Cruz',
        priority: 'high',
        status: 'in_progress',
        due_date: 'Jun 18, 5:00 PM',
        is_escalated: false,
    },
    {
        id: '#MS-8905',
        concern_id: 'c2',
        concern_title: 'Street flooding — Riverside Ave.',
        location: 'Riverside Ave., Zone 3',
        assignee: 'Maria Santos',
        priority: 'high',
        status: 'acknowledged',
        due_date: 'Jun 18, 12:00 PM',
    },
    {
        id: '#MS-8910',
        concern_id: 'c8',
        concern_title: 'Fallen electrical line',
        location: 'Zone 4, Block 12',
        assignee: null,
        priority: 'high',
        status: 'assigned',
        due_date: 'Jun 17, 6:00 PM',
        is_overdue: true,
        is_escalated: true,
    },
    {
        id: '#MS-8890',
        concern_id: 'c5',
        concern_title: 'Street light repair',
        location: 'Block 3, Phase 2',
        assignee: 'Pedro Reyes',
        priority: 'low',
        status: 'verified',
        due_date: 'Jun 16, 5:00 PM',
    },
    {
        id: '#MS-8888',
        concern_id: 'c4',
        concern_title: 'Illegal dumping cleanup',
        location: 'Market rear alley',
        assignee: 'Juan Dela Cruz',
        priority: 'med',
        status: 'completed',
        due_date: 'Jun 17, 3:00 PM',
    },
    {
        id: '#MS-8885',
        concern_id: 'c3',
        concern_title: 'Noise complaint follow-up',
        location: 'Phase 2, Unit 7',
        assignee: 'Ana Lopez',
        priority: 'med',
        status: 'assigned',
        due_date: 'Jun 19, 8:00 PM',
        is_overdue: true,
    },
    {
        id: '#MS-8880',
        concern_id: 'c6',
        concern_title: 'VAWC case — welfare check',
        location: 'Withheld — private',
        assignee: 'Maria Santos',
        priority: 'high',
        status: 'in_progress',
        due_date: 'Jun 17, 11:59 PM',
    },
    {
        id: '#MS-8875',
        concern_id: 'c7',
        concern_title: 'Cancelled — duplicate report',
        location: 'N/A',
        assignee: null,
        priority: 'low',
        status: 'cancelled',
        due_date: '—',
    },
];

export function missionCounts(missions: AdminMission[]) {
    return {
        all: missions.length,
        assigned: missions.filter((m) => m.status === 'assigned').length,
        acknowledged: missions.filter((m) => m.status === 'acknowledged').length,
        in_progress: missions.filter((m) => m.status === 'in_progress').length,
        completed: missions.filter((m) => m.status === 'completed').length,
        verified: missions.filter((m) => m.status === 'verified').length,
        overdue: missions.filter((m) => m.is_overdue || m.is_escalated).length,
    };
}

export const demoMapPins: AdminMapPin[] = [
    {
        id: 'mp1',
        lat: 14.6012,
        lng: 120.9821,
        title: 'Clogged drainage',
        severity: 'high',
        report_id: '#RP-1042',
        concern_id: 'c1',
        location_label: 'Mabini St. corner Rizal Ave.',
        type_icon: 'drainage',
        incident_type: 'Clogged drainage',
        status: 'active',
        has_mission: true,
        mission_id: '#MS-8902',
        ai_severity: 88,
    },
    {
        id: 'mp2',
        lat: 14.5984,
        lng: 120.9862,
        title: 'Street flooding',
        severity: 'high',
        report_id: '#RP-1041',
        concern_id: 'c2',
        location_label: 'Riverside Ave., Zone 3',
        type_icon: 'flood',
        incident_type: 'Street flooding',
        status: 'active',
        has_mission: true,
        mission_id: '#MS-8905',
        ai_severity: 76,
    },
    {
        id: 'mp3',
        lat: 14.5971,
        lng: 120.9814,
        title: 'Noise complaint',
        severity: 'medium',
        report_id: '#RP-1038',
        concern_id: 'c3',
        location_label: 'Phase 2, Unit 7',
        type_icon: 'noise',
        incident_type: 'Noise complaint',
        status: 'pending',
        has_mission: true,
        mission_id: '#MS-8885',
        ai_severity: 42,
    },
    {
        id: 'mp4',
        lat: 14.6023,
        lng: 120.9881,
        title: 'Illegal dumping',
        severity: 'medium',
        report_id: '#RP-1035',
        concern_id: 'c4',
        location_label: 'Market rear alley',
        type_icon: 'waste',
        incident_type: 'Illegal dumping',
        status: 'active',
        has_mission: true,
        mission_id: '#MS-8888',
        ai_severity: 55,
    },
    {
        id: 'mp5',
        lat: 14.5968,
        lng: 120.9835,
        title: 'Street light out',
        severity: 'low',
        report_id: '#RP-1030',
        concern_id: 'c5',
        location_label: 'Block 3, Phase 2',
        type_icon: 'light',
        incident_type: 'Street light out',
        status: 'resolved',
        has_mission: true,
        mission_id: '#MS-8890',
        ai_severity: 35,
    },
    {
        id: 'mp6',
        lat: 14.6018,
        lng: 120.9848,
        title: 'Fallen electrical line',
        severity: 'critical',
        report_id: '#RP-1019',
        concern_id: 'c8',
        location_label: 'Zone 4, Block 12',
        type_icon: 'fire',
        incident_type: 'Fallen electrical line',
        status: 'active',
        has_mission: true,
        mission_id: '#MS-8910',
        ai_severity: 95,
    },
    {
        id: 'mp7',
        lat: 14.5998,
        lng: 120.9855,
        title: 'Open manhole',
        severity: 'high',
        report_id: '#RP-1015',
        concern_id: 'c9',
        location_label: 'Zone 4, near barangay hall',
        type_icon: 'drainage',
        incident_type: 'Open manhole',
        status: 'pending',
        has_mission: false,
        ai_severity: 72,
    },
    {
        id: 'mp8',
        lat: 14.6005,
        lng: 120.9802,
        title: 'Garbage pile-up',
        severity: 'medium',
        report_id: '#RP-1012',
        concern_id: 'c10',
        location_label: 'Zone 4, Block 8',
        type_icon: 'waste',
        incident_type: 'Garbage pile-up',
        status: 'active',
        has_mission: false,
        ai_severity: 48,
    },
];

export const demoHotspots: AdminMapHotspot[] = [
    {
        id: 'h1',
        lat: 14.601,
        lng: 120.9835,
        radius_m: 350,
        label: 'Zone 4 — infrastructure cluster',
        report_count: 5,
        risk_level: 'high',
    },
    {
        id: 'h2',
        lat: 14.5985,
        lng: 120.986,
        radius_m: 280,
        label: 'Riverside — flooding hotspot',
        report_count: 3,
        risk_level: 'medium',
    },
    {
        id: 'h3',
        lat: 14.602,
        lng: 120.988,
        radius_m: 200,
        label: 'Market area — sanitation',
        report_count: 2,
        risk_level: 'low',
    },
];

export function mapFilterCounts(pins: AdminMapPin[]) {
    const count = (fn: (p: AdminMapPin) => boolean) => pins.filter(fn).length;

    return {
        sev_all: pins.length,
        sev_critical: count((p) => p.severity === 'critical'),
        sev_high: count((p) => p.severity === 'high'),
        sev_medium: count((p) => p.severity === 'medium'),
        sev_low: count((p) => p.severity === 'low'),
        status_all: pins.length,
        status_active: count((p) => p.status === 'active'),
        status_pending: count((p) => p.status === 'pending'),
        status_resolved: count((p) => p.status === 'resolved'),
        type_all: pins.length,
        type_fire: count((p) => p.type_icon === 'fire'),
        type_flood: count((p) => p.type_icon === 'flood'),
        type_drainage: count((p) => p.type_icon === 'drainage'),
        type_waste: count((p) => p.type_icon === 'waste'),
        type_noise: count((p) => p.type_icon === 'noise'),
        type_light: count((p) => p.type_icon === 'light'),
    };
}

export function pinsFromReports(reports: AdminReport[]): AdminMapPin[] {
    return reports
        .filter((r) => !r.location.toLowerCase().includes('withheld') && !r.location.startsWith('Duplicate'))
        .map((r, i) => ({
            id: `mp-${r.concern_id}`,
            lat: 14.5995 + (i % 4) * 0.002 - 0.003,
            lng: 120.9842 + (Math.floor(i / 4) % 3) * 0.003 - 0.004,
            title: r.incident_type,
            severity: severityFromScore(r.ai_severity),
            report_id: r.id,
            concern_id: r.concern_id,
            location_label: r.location,
            type_icon: r.type_icon,
            incident_type: r.incident_type,
            status:
                r.queue_status === 'active' || r.status === 'ongoing'
                    ? 'active'
                    : r.status === 'done'
                      ? 'resolved'
                      : 'pending',
            has_mission: false,
            ai_severity: r.ai_severity,
        }));
}

export const demoAnnouncements: AdminAnnouncement[] = [
    {
        id: 'ann-001',
        title: 'Typhoon season preparedness advisory',
        body: 'Barangay residents are advised to prepare emergency kits and monitor PAGASA updates. Evacuation centers will open at the barangay hall if Signal No. 2 is raised for our area.',
        image_url: 'https://images.unsplash.com/photo-1527482791421-259302b81383?w=800&q=80',
        is_published: true,
        published_at: 'Jun 16, 8:00 AM',
        author_name: 'ADMIN001',
        created_at: 'Jun 16, 7:45 AM',
        updated_at: 'Jun 16, 8:00 AM',
    },
    {
        id: 'ann-002',
        title: 'Scheduled water interruption — Zone 3 & 4',
        body: 'Maynilad will conduct pipeline maintenance on Jun 18 from 9:00 AM to 4:00 PM. Affected areas: Riverside Ave., Block 8–12, and surrounding streets. Please store water in advance.',
        is_published: true,
        published_at: 'Jun 15, 2:30 PM',
        author_name: 'ADMIN001',
        created_at: 'Jun 15, 2:00 PM',
        updated_at: 'Jun 15, 2:30 PM',
    },
    {
        id: 'ann-003',
        title: 'Barangay assembly — quarterly report',
        body: 'All purok leaders and interested residents are invited to the quarterly barangay assembly on Jun 22, 6:00 PM at the covered court. Agenda includes flood mitigation updates and SK project reports.',
        is_published: false,
        published_at: null,
        author_name: 'ADMIN001',
        created_at: 'Jun 17, 10:00 AM',
        updated_at: 'Jun 17, 10:00 AM',
    },
    {
        id: 'ann-004',
        title: 'Public appeal: missing senior citizen',
        body: 'The family of Lola Carmen Reyes, 78, requests information on her whereabouts last seen near the market on Jun 14. Contact barangay tanod hotline or visit the hall if you have leads.',
        image_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80',
        is_published: true,
        published_at: 'Jun 14, 5:15 PM',
        author_name: 'ADMIN001',
        created_at: 'Jun 14, 4:50 PM',
        updated_at: 'Jun 14, 5:15 PM',
    },
    {
        id: 'ann-005',
        title: 'Road closure — Mabini St. drainage works',
        body: 'Mabini St. will be partially closed Jun 19–21 for drainage repair linked to concern #RP-1042. Use alternate routes via Rizal Ave. Traffic enforcers will be on site.',
        is_published: false,
        published_at: null,
        author_name: 'ADMIN001',
        created_at: 'Jun 17, 11:30 AM',
        updated_at: 'Jun 17, 11:30 AM',
    },
];

export function announcementCounts(announcements: AdminAnnouncement[]) {
    return {
        all: announcements.length,
        published: announcements.filter((a) => a.is_published).length,
        draft: announcements.filter((a) => !a.is_published).length,
    };
}

export function findAnnouncement(id: string): AdminAnnouncement | undefined {
    return demoAnnouncements.find((a) => a.id === id);
}

export const demoResidents: AdminResident[] = [
    {
        id: 'u-res-001',
        account_id: 'RES001',
        full_name: 'Juan Dela Cruz',
        email: 'resident@demo.local',
        mobile: '09171234567',
        address: 'Block 3, Phase 2, Barangay Demo',
        verification_status: 'approved',
        civic_xp: 240,
        report_count: 8,
        badge_count: 3,
        digital_id_code: 'BL-2024-00421',
        joined_at: 'Jan 12, 2024',
    },
    {
        id: 'u-res-002',
        account_id: 'RES002',
        full_name: 'Maria Santos',
        email: 'maria.santos@demo.local',
        mobile: '09189876543',
        address: 'Zone 4, Block 12',
        verification_status: 'approved',
        civic_xp: 185,
        report_count: 6,
        badge_count: 2,
        digital_id_code: 'BL-2024-00455',
        joined_at: 'Feb 3, 2024',
    },
    {
        id: 'u-res-003',
        account_id: 'RES003',
        full_name: 'Pedro Reyes',
        email: null,
        mobile: '09201234567',
        address: 'Riverside Ave., Unit 5',
        verification_status: 'in_progress',
        civic_xp: 45,
        report_count: 2,
        badge_count: 0,
        digital_id_code: null,
        joined_at: 'Jun 10, 2026',
    },
    {
        id: 'u-res-004',
        account_id: 'RES004',
        full_name: 'Ana Lopez',
        email: 'ana.lopez@demo.local',
        mobile: '09351112233',
        address: 'Market rear alley, Phase 1',
        verification_status: 'pending',
        civic_xp: 0,
        report_count: 0,
        badge_count: 0,
        digital_id_code: null,
        joined_at: 'Jun 16, 2026',
    },
    {
        id: 'u-res-005',
        account_id: 'RES005',
        full_name: 'Ricardo Tan',
        email: 'ricardo.tan@demo.local',
        mobile: '09451239876',
        address: 'Mabini St. corner Rizal Ave.',
        verification_status: 'approved',
        civic_xp: 320,
        report_count: 12,
        badge_count: 4,
        digital_id_code: 'BL-2023-01288',
        joined_at: 'Nov 8, 2023',
    },
    {
        id: 'u-res-006',
        account_id: 'RES006',
        full_name: 'Elena Villanueva',
        email: null,
        mobile: '09567890123',
        address: 'Phase 2, Unit 7',
        verification_status: 'rejected',
        civic_xp: 10,
        report_count: 1,
        badge_count: 0,
        digital_id_code: null,
        joined_at: 'May 20, 2026',
    },
    {
        id: 'u-res-007',
        account_id: 'RES007',
        full_name: 'Carlos Mendoza',
        email: 'carlos.m@demo.local',
        mobile: '09671234567',
        address: 'Zone 3, Block 8',
        verification_status: 'approved',
        civic_xp: 98,
        report_count: 4,
        badge_count: 1,
        digital_id_code: 'BL-2025-00012',
        joined_at: 'Mar 15, 2025',
    },
];

const residentDetails: Record<string, Omit<AdminResidentDetail, keyof AdminResident>> = {
    'u-res-001': {
        birthday: 'Mar 14, 1990',
        age_years: 35,
        national_id_masked: 'XXXX-XXXX-4421',
        citizenship_status: 'Filipino',
        gender: 'Male',
        zip_code: '1000',
        map_lat: 14.5998,
        map_lng: 120.9845,
        emergency_contact: {
            name: 'Maria Dela Cruz',
            relationship: 'Spouse',
            phone: '09181234567',
        },
        badges: [
            { id: 'b1', name: 'First Reporter', description: 'Submitted first valid concern', earned_at: 'Jan 15, 2024' },
            { id: 'b2', name: 'Community Voice', description: '5 reports confirmed by admin', earned_at: 'Apr 2, 2024' },
            { id: 'b3', name: 'Flood Watcher', description: 'Reported 3 flooding incidents', earned_at: 'Aug 10, 2024' },
        ],
        reports: [
            { id: '#RP-1042', concern_id: 'c1', title: 'Clogged drainage on Mabini St.', category: 'Infrastructure', status: 'active', visibility: 'public', submitted_at: 'Jun 17, 9:14 AM' },
            { id: '#RP-1030', concern_id: 'c5', title: 'Street light out', category: 'Infrastructure', status: 'resolved', visibility: 'public', submitted_at: 'Jun 15, 6:30 PM' },
            { id: '#RP-1020', concern_id: 'c11', title: 'Stray dogs near school', category: 'Sanitation', status: 'resolved', visibility: 'public', submitted_at: 'Jun 10, 3:00 PM' },
        ],
        xp_events: [
            { id: 'xp1', reason: 'Valid report submitted', amount: 10, at: 'Jun 17, 9:14 AM' },
            { id: 'xp2', reason: 'Concern resolved', amount: 5, at: 'Jun 16, 4:00 PM' },
            { id: 'xp3', reason: 'Upvote received', amount: 2, at: 'Jun 15, 8:00 PM' },
        ],
        activities: [
            { id: 'act1', date: 'Jun 17, 2026', type: 'mission', description: 'Reported clogged drainage #RP-1042', status: 'active' },
            { id: 'act2', date: 'Jun 15, 2026', type: 'mission', description: 'Reported streetlight outage #RP-1030', status: 'resolved' },
            { id: 'act3', date: 'Jun 14, 2026', type: 'broadcast', description: 'Received: Typhoon preparedness advisory', status: 'acknowledged' },
            { id: 'act4', date: 'Jun 10, 2026', type: 'mission', description: 'Community cleanup participant', status: 'complete' },
        ],
        documents: [
            { id: 'doc1', name: 'National_ID_Juan.pdf', meta: 'Verified Jan 2024', size: '2.4 MB', status: 'verified' },
            { id: 'doc2', name: 'Proof_of_Residency.pdf', meta: 'Updated Mar 2024', size: '1.1 MB', status: 'updated' },
            { id: 'doc3', name: 'Barangay_Clearance.pdf', meta: 'Pending review', size: '0.8 MB', status: 'pending' },
        ],
    },
    'u-res-002': {
        birthday: 'Aug 22, 1988',
        age_years: 37,
        national_id_masked: 'XXXX-XXXX-4455',
        citizenship_status: 'Filipino',
        gender: 'Female',
        zip_code: '1000',
        map_lat: 14.601,
        map_lng: 120.983,
        emergency_contact: {
            name: 'Jose Santos',
            relationship: 'Spouse',
            phone: '09191112233',
        },
        badges: [
            { id: 'b8', name: 'Community Voice', description: '5 reports confirmed by admin', earned_at: 'May 1, 2024' },
            { id: 'b9', name: 'First Reporter', description: 'Submitted first valid concern', earned_at: 'Feb 5, 2024' },
        ],
        reports: [],
        xp_events: [],
        activities: [
            { id: 'act5', date: 'Jun 16, 2026', type: 'broadcast', description: 'Received: Water interruption advisory', status: 'acknowledged' },
        ],
        documents: [
            { id: 'doc4', name: 'National_ID_Maria.pdf', meta: 'Verified Feb 2024', size: '2.2 MB', status: 'verified' },
        ],
    },
    'u-res-005': {
        birthday: 'Jul 22, 1985',
        age_years: 40,
        national_id_masked: 'XXXX-XXXX-1288',
        citizenship_status: 'Filipino',
        gender: 'Male',
        zip_code: '1000',
        map_lat: 14.6012,
        map_lng: 120.9821,
        emergency_contact: {
            name: 'Lisa Tan',
            relationship: 'Spouse',
            phone: '09459876543',
        },
        badges: [
            { id: 'b4', name: 'Civic Champion', description: 'Top 5 XP in barangay', earned_at: 'Dec 1, 2024' },
            { id: 'b5', name: 'First Reporter', description: 'Submitted first valid concern', earned_at: 'Nov 10, 2023' },
            { id: 'b6', name: 'Community Voice', description: '5 reports confirmed by admin', earned_at: 'Jan 5, 2024' },
            { id: 'b7', name: 'Early Adopter', description: 'Joined during pilot phase', earned_at: 'Nov 8, 2023' },
        ],
        reports: [
            { id: '#RP-1041', concern_id: 'c2', title: 'Street flooding — Riverside Ave.', category: 'Infrastructure', status: 'active', visibility: 'public', submitted_at: 'Jun 17, 8:42 AM' },
            { id: '#RP-1035', concern_id: 'c4', title: 'Illegal dumping', category: 'Sanitation', status: 'under_review', visibility: 'public', submitted_at: 'Jun 16, 4:05 PM' },
        ],
        xp_events: [
            { id: 'xp4', reason: 'Valid report submitted', amount: 10, at: 'Jun 17, 8:42 AM' },
            { id: 'xp5', reason: 'Badge earned: Civic Champion', amount: 25, at: 'Dec 1, 2024' },
        ],
        activities: [
            { id: 'act6', date: 'Jun 17, 2026', type: 'mission', description: 'Reported street flooding #RP-1041', status: 'active' },
            { id: 'act7', date: 'Jun 16, 2026', type: 'mission', description: 'Reported illegal dumping #RP-1035', status: 'pending' },
            { id: 'act8', date: 'Dec 1, 2024', type: 'mission', description: 'Earned Civic Champion badge', status: 'complete' },
        ],
        documents: [
            { id: 'doc5', name: 'National_ID_Ricardo.pdf', meta: 'Verified Nov 2023', size: '2.5 MB', status: 'verified' },
            { id: 'doc6', name: 'Proof_of_Residency.pdf', meta: 'Updated Jan 2024', size: '1.0 MB', status: 'verified' },
        ],
    },
};

const defaultDetail: Omit<AdminResidentDetail, keyof AdminResident> = {
    birthday: '—',
    age_years: null,
    national_id_masked: null,
    citizenship_status: 'Filipino',
    gender: '—',
    zip_code: null,
    map_lat: 14.5995,
    map_lng: 120.9842,
    emergency_contact: null,
    badges: [],
    reports: [],
    xp_events: [],
    activities: [],
    documents: [],
};

export function residentCounts(residents: AdminResident[]) {
    return {
        all: residents.length,
        approved: residents.filter((r) => r.verification_status === 'approved').length,
        pending: residents.filter((r) => r.verification_status === 'pending').length,
        in_progress: residents.filter((r) => r.verification_status === 'in_progress').length,
        rejected: residents.filter((r) => r.verification_status === 'rejected').length,
    };
}

export function findResident(id: string): AdminResidentDetail | undefined {
    const base = demoResidents.find((r) => r.id === id || r.account_id === id);
    if (!base) return undefined;
    const extra = residentDetails[base.id] ?? defaultDetail;
    return { ...base, ...extra };
}
